version: '3.8'

services:
  app:
    container_name: todo-app-client
    image: "mcr.microsoft.com/devcontainers/typescript-node:18-bullseye"
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    environment:
      VITE_APP_API_ENDPOINT: http://localhost:8080

    # ports:
    # - "8080:8080"

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
